# Generated by Django 2.1.4 on 2019-01-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(null=True, upload_to='base/static'),
        ),
    ]
