# Generated by Django 2.1.4 on 2018-12-31 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20181231_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.FileField(null=True, upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shoppinguser',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinguser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن نامعتبر است', regex='^((\\+|00)\\d{11,12})|(09\\d{9})$')]),
        ),
        migrations.AlterField(
            model_name='shoppinguser',
            name='province',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
