# Generated by Django 2.1.4 on 2019-02-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinguser',
            name='credit',
            field=models.IntegerField(null=True),
        ),
    ]
