# Generated by Django 2.1.4 on 2019-01-01 14:04

from django.db import migrations
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20190101_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location_lat',
            field=osm_field.fields.LatitudeField(null=True, validators=[osm_field.validators.validate_latitude]),
        ),
        migrations.AddField(
            model_name='product',
            name='location_lon',
            field=osm_field.fields.LongitudeField(null=True, validators=[osm_field.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=osm_field.fields.OSMField(lat_field='location_lat', lon_field='location_lon'),
        ),
    ]
