# Generated by Django 2.1.4 on 2019-02-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_shoppinguser_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinguser',
            name='credit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
