# Generated by Django 2.1.4 on 2019-01-01 14:04

from django.db import migrations
import osm_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20190101_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=osm_field.fields.OSMField(lat_field='location_lat', lon_field='location_lon'),
        ),
    ]
