# Generated by Django 2.1.4 on 2019-01-01 14:06

from django.db import migrations
import osm_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20190101_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location_lat',
            new_name='loc_lat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='location_lon',
            new_name='loc_lon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.AddField(
            model_name='product',
            name='loc',
            field=osm_field.fields.OSMField(default=1, lat_field='loc_lat', lon_field='loc_lon'),
            preserve_default=False,
        ),
    ]
