# Generated by Django 2.1.4 on 2019-02-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20190202_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinguser',
            name='random_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
