# Generated by Django 2.1.4 on 2019-02-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_shoppinguser_random_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinguser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shoppinguser',
            name='referrer_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
