# Generated by Django 2.1.4 on 2019-01-01 14:12

from django.db import migrations
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_remove_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='loc_lat',
            field=osm_field.fields.LatitudeField(default=1, validators=[osm_field.validators.validate_latitude]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='loc_lon',
            field=osm_field.fields.LongitudeField(default=1, validators=[osm_field.validators.validate_longitude]),
            preserve_default=False,
        ),
    ]
