# Generated by Django 2.1.4 on 2019-01-01 14:12

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_auto_20190101_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1, max_length=63),
            preserve_default=False,
        ),
    ]
