# Generated by Django 2.1.4 on 2019-02-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_auction_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='finished',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
