# Generated by Django 2.1.4 on 2019-01-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
