# Generated by Django 2.1.4 on 2019-02-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_auction_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_subcategory',
            field=models.CharField(choices=[('لپ تاپ', 'لپ تاپ'), ('تلفن همراه', 'تلفن همراه'), ('دوربین', 'دوربین'), ('تلویزیون', 'تلویزیون'), ('بلندگو', 'بلندگو'), ('تلویزیون', 'تلویزیون'), ('تبلت', 'تبلت'), ('هارد، فلش و SSD', 'تلویزیون'), ('مچ\u200cبند و ساعت هوشمند', 'تلویزیون'), ('هدفون، هدست', 'تلویزیون')], max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='health_subcategory',
            field=models.CharField(choices=[('لوازم آرایشی', 'لوازم آرایشی'), ('کرم', 'کرم'), ('شامپو', 'شامپو'), ('ضد تعریق', 'ضد تعریق'), ('دهان\u200cشوی', 'دهان\u200cشوی')], max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('digital_prods', 'لوازم دیجیتال'), ('pretty_prods', 'لوازم تزیینی'), ('health_prods', 'لوازم بهداشتی'), ('cars', 'خودرو'), ('sport_prods', 'لوازم ورزشی'), ('cooking_prods', 'لوازم آشپزی'), ('house', 'مسکن'), ('electrical_prods', 'لوازم برقی')], max_length=140, null=True),
        ),
    ]
