# Generated by Django 2.1.4 on 2019-02-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_auto_20190215_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='shopping.ShoppingUser')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='shopping.ShoppingUser')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cars_subcategory',
            field=models.CharField(choices=[('فرمان', 'فرمان'), ('دنده', 'دنده'), ('روکش صندلی', 'روکش صندلی'), ('برف\u200c\u200cپاک\u200cکن', 'برف\u200c\u200cپاک\u200cکن'), ('باتری ماشین', 'باتری ماشین')], max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cooking_subcategory',
            field=models.CharField(choices=[('قابلمه', 'قابلمه'), ('ماهی\u200cتابه', 'ماهی\u200cتابه'), ('کف\u200cگیر', 'کف\u200cگیر'), ('قاشق\u200cچنگال', 'قاشق\u200cچنگال'), ('بشفاب', 'بشفاب')], max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='house_subcategory',
            field=models.CharField(choices=[('یخچال', 'یخچال'), ('مبل', 'مبل'), ('پرده', 'پرده'), ('میز', 'میز'), ('صندلی', 'صندلی')], max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pretty_subcategory',
            field=models.CharField(choices=[('تابلو', 'تابلو'), ('مجسمه', 'مجسمه'), ('شمع\u200cدونی', 'شمع\u200cدونی'), ('آینه', 'آینه'), ('پرده', 'پرده')], max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sports_subcategory',
            field=models.CharField(choices=[('توپ', 'توپ'), ('گرم\u200cکن', 'گرم\u200cکن'), ('دست\u200cکش دروازه\u200cبانی', 'دست\u200cکش دروازه\u200cبانی'), ('لباس شنا', 'لباس شنا'), ('عینک شنا', 'عینک شنا')], max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('category_id_1', 'لوازم دیجیتال'), ('category_id_2', 'لوازم تزیینی'), ('category_id_3', 'لوازم بهداشتی'), ('category_id_4', 'خودرو'), ('category_id_5', 'لوازم ورزشی'), ('category_id_6', 'لوازم آشپزی'), ('category_id_7', 'لوزام مسکن')], max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital_subcategory',
            field=models.CharField(choices=[('لپ تاپ', 'لپ تاپ'), ('تلفن همراه', 'تلفن همراه'), ('دوربین', 'دوربین'), ('تلویزیون', 'تلویزیون'), ('بلندگو', 'بلندگو'), ('تبلت', 'تبلت'), ('هارد، فلش و SSD', 'هارد، فلش و SSD'), ('مچ\u200cبند و ساعت هوشمند', 'مچ\u200cبند و ساعت هوشمند'), ('هدفون، هدست', 'هدفون، هدست')], max_length=140, null=True),
        ),
    ]
