# Generated by Django 2.1.4 on 2019-02-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_auto_20190216_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinguser',
            name='has_new_messages',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
